### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by ghost** [yuanying/docker-dovecot#1]
Hi
i run this command 
docker run -d \
  -e "MYSQL_PORT_3306_TCP_ADDR=128.199.203.70" \
  -e "MYSQL_PORT_3306_TCP_PORT=3306" \
  -e "POSTFIX_MYSQL_PASSWORD=ZtO4OieSBkrUtBg8" \
  -h 'serverha.tk' \
  -v /var/vmail:/var/vmail \
  -p 993:993 \
  amirarabi/docker-dovecot

and this message appear but no container created
be0f7326342b9c46b07b2a95babde722a0a2e4db1fdd7f97485025d3c284b43b

your other docker file (docker-postfix and docker-postfixadmin) have an error in build step

**Comment by yuanying** [comment]
I created this Dockerfile for precise, so I fix to from statement to from ubuntu:precise
